### ISSUE TITLE
Wrong Malware State on Timeout

### ISSUE THREAD

**Issue by 0pendev** [Kn0wl3dge/AutoDetours#65]
When one of the jobs states is "time out" while the other has a "done" state, the malware stays in a "Running state".

**Comment by Kn0wl3dge** [comment]
This is due to the following code snippet. In the case you're mentioning, we directly go to the "else" condition.
https://github.com/Kn0wl3dge/AutoDetours/blob/d9bd15a65e7207e92b4fb415f91153eceb03f9a7/backend/malwares/serializers.py#L33-L41

I will update this code to support the "Timed Out" status of a job.
